import { useNavigation } from '@react-navigation/native';
export const articles = [
    {
        id: 1,
        imageSource:require('../assets/article1Img.png'),
        title:"Christmas menu for child",
        paragraph1:"Сhristmas party season is on its way, and with so much to think about we want to make sure you have everything you need for your baby and toddler Christmas recipes.",
        punkt1:"1. Carrot Cake Muffins",
        paragraph2:"For baby carrot muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze.",
        articlePage1Img:require('../assets/articlePage1Img.png'),
        articlePage2Img:require('../assets/mealVideoImg.png'),
        punkt2:"2. Christmas menu for children",
        paragraph3:"For baby led weaning muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze. ",
        articlePage3Img:require('../assets/articlePage2Img.png'),
        articlePage4Img:require('../assets/productMeal2Img.png'),
        punkt3:"3. Christmas menu for children",
        articlePage5Img:require('../assets/video4.png'),
        articlePage6Img:require('../assets/articlePage3Img.png'),
        paragraph4:"For baby led weaning muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze. So make lots, freeze and the night before you (or Santa Claus) wants to eat them you can remove from the freezer to defrost.",
    },
    {
      id: 2,
      imageSource:require('../assets/article2Img.png'),
      title:"Feeding Issues: Baby Spitting Up",
      paragraph1:"Сhristmas party season is on its way, and with so much to think about we want to make sure you have everything you need for your baby and toddler Christmas recipes.",
      punkt1:"1. Carrot Cake Muffins",
      paragraph2:"For baby carrot muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze.",
      articlePage1Img:require('../assets/articlePage1Img.png'),
      articlePage2Img:require('../assets/mealVideoImg.png'),
      punkt2:"2. Christmas menu for children",
      paragraph3:"For baby led weaning muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze. ",
      articlePage3Img:require('../assets/articlePage2Img.png'),
      articlePage4Img:require('../assets/productMeal2Img.png'),
      punkt3:"3. Christmas menu for children",
      articlePage5Img:require('../assets/video4.png'),
      articlePage6Img:require('../assets/articlePage3Img.png'),
      paragraph4:"For baby led weaning muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze. So make lots, freeze and the night before you (or Santa Claus) wants to eat them you can remove from the freezer to defrost.",
    },
    { id: 3,
        imageSource:require('../assets/article3Img.png'),
        title:"6 Tips for Traveling with Baby",
        paragraph1:"Сhristmas party season is on its way, and with so much to think about we want to make sure you have everything you need for your baby and toddler Christmas recipes.",
        punkt1:"1. Carrot Cake Muffins",
        paragraph2:"For baby carrot muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze.",
        articlePage1Img:require('../assets/articlePage1Img.png'),
        articlePage2Img:require('../assets/mealVideoImg.png'),
        punkt2:"2. Christmas menu for children",
        paragraph3:"For baby led weaning muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze. ",
        articlePage3Img:require('../assets/articlePage2Img.png'),
        articlePage4Img:require('../assets/productMeal2Img.png'),
        punkt3:"3. Christmas menu for children",
        articlePage5Img:require('../assets/video4.png'),
        articlePage6Img:require('../assets/articlePage3Img.png'),
        paragraph4:"For baby led weaning muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze. So make lots, freeze and the night before you (or Santa Claus) wants to eat them you can remove from the freezer to defrost.",
    },
    {
      id: 4,
      imageSource:require('../assets/article4Img.png'),
      title:"How Babies Develop Allergies",
      paragraph1:"Сhristmas party season is on its way, and with so much to think about we want to make sure you have everything you need for your baby and toddler Christmas recipes.",
      punkt1:"1. Carrot Cake Muffins",
      paragraph2:"For baby carrot muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze.",
      articlePage1Img:require('../assets/articlePage1Img.png'),
      articlePage2Img:require('../assets/mealVideoImg.png'),
      punkt2:"2. Christmas menu for children",
      paragraph3:"For baby led weaning muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze. ",
      articlePage3Img:require('../assets/articlePage2Img.png'),
      articlePage4Img:require('../assets/productMeal2Img.png'),
      punkt3:"3. Christmas menu for children",
      articlePage5Img:require('../assets/video4.png'),
      articlePage6Img:require('../assets/articlePage3Img.png'),
      paragraph4:"For baby led weaning muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze. So make lots, freeze and the night before you (or Santa Claus) wants to eat them you can remove from the freezer to defrost.",
    },
    
    {id: 5,
        imageSource:require('../assets/allergiesImg.png'),
      title:"What is a Food Allergy?",
      paragraph1:"Сhristmas party season is on its way, and with so much to think about we want to make sure you have everything you need for your baby and toddler Christmas recipes.",
      punkt1:"1. Carrot Cake Muffins",
      paragraph2:"For baby carrot muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze.",
      articlePage1Img:require('../assets/articlePage1Img.png'),
      articlePage2Img:require('../assets/mealVideoImg.png'),
      punkt2:"2. Christmas menu for children",
      paragraph3:"For baby led weaning muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze. ",
      articlePage3Img:require('../assets/articlePage2Img.png'),
      articlePage4Img:require('../assets/productMeal2Img.png'),
      punkt3:"3. Christmas menu for children",
      articlePage5Img:require('../assets/video4.png'),
      articlePage6Img:require('../assets/articlePage3Img.png'),
      paragraph4:"For baby led weaning muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze. So make lots, freeze and the night before you (or Santa Claus) wants to eat them you can remove from the freezer to defrost.",
    },
    {id: 6,
        imageSource:require('../assets/article5Img.png'),
        title:"Cow`s Milk Allergies in Babies",
        paragraph1:"Сhristmas party season is on its way, and with so much to think about we want to make sure you have everything you need for your baby and toddler Christmas recipes.",
        punkt1:"1. Carrot Cake Muffins",
        paragraph2:"For baby carrot muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze.",
        articlePage1Img:require('../assets/articlePage1Img.png'),
        articlePage2Img:require('../assets/mealVideoImg.png'),
        punkt2:"2. Christmas menu for children",
        paragraph3:"For baby led weaning muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze. ",
        articlePage3Img:require('../assets/articlePage2Img.png'),
        articlePage4Img:require('../assets/productMeal2Img.png'),
        punkt3:"3. Christmas menu for children",
        articlePage5Img:require('../assets/video4.png'),
        articlePage6Img:require('../assets/articlePage3Img.png'),
        paragraph4:"For baby led weaning muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze. So make lots, freeze and the night before you (or Santa Claus) wants to eat them you can remove from the freezer to defrost.",
    },
    {id: 7,
        imageSource:require('../assets/article6Img.png'),
        title:"How Babies Develop Allergies",
        paragraph1:"Сhristmas party season is on its way, and with so much to think about we want to make sure you have everything you need for your baby and toddler Christmas recipes.",
        punkt1:"1. Carrot Cake Muffins",
        paragraph2:"For baby carrot muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze.",
        articlePage1Img:require('../assets/articlePage1Img.png'),
        articlePage2Img:require('../assets/mealVideoImg.png'),
        punkt2:"2. Christmas menu for children",
        paragraph3:"For baby led weaning muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze. ",
        articlePage3Img:require('../assets/articlePage2Img.png'),
        articlePage4Img:require('../assets/productMeal2Img.png'),
        punkt3:"3. Christmas menu for children",
        articlePage5Img:require('../assets/video4.png'),
        articlePage6Img:require('../assets/articlePage3Img.png'),
        paragraph4:"For baby led weaning muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze. So make lots, freeze and the night before you (or Santa Claus) wants to eat them you can remove from the freezer to defrost.",
    },
    {id: 8,
        imageSource:require('../assets/article7Img.png'),
        title:"Common Food Allergies",
        paragraph1:"Сhristmas party season is on its way, and with so much to think about we want to make sure you have everything you need for your baby and toddler Christmas recipes.",
        punkt1:"1. Carrot Cake Muffins",
        paragraph2:"For baby carrot muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze.",
        articlePage1Img:require('../assets/articlePage1Img.png'),
        articlePage2Img:require('../assets/mealVideoImg.png'),
        punkt2:"2. Christmas menu for children",
        paragraph3:"For baby led weaning muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze. ",
        articlePage3Img:require('../assets/articlePage2Img.png'),
        articlePage4Img:require('../assets/productMeal2Img.png'),
        punkt3:"3. Christmas menu for children",
        articlePage5Img:require('../assets/video4.png'),
        articlePage6Img:require('../assets/articlePage3Img.png'),
        paragraph4:"For baby led weaning muffins are just brilliant! They can be made well ahead of time and the best part is that they freeze. So make lots, freeze and the night before you (or Santa Claus) wants to eat them you can remove from the freezer to defrost.",
    },
  ];
  

  