import { StyleSheet } from 'react-native';

const globalStyles = StyleSheet.create({
    welcome: {
        color: 'black',
        fontFamily: 'Caladea-Bold',
        fontSize: 48,
    },
    videoTitle: {
        color: 'black',
        fontFamily: 'RadioCanada',
        fontSize: 28,
    },
    videoIngridientsTitle: {
        color: 'black',
        fontFamily: 'Caladea-Bold',
        fontSize: 28,
    },
    title: {
        color: 'white',
        fontFamily: 'Caladea-Bold',
        fontSize: 24,
    },
    title2: {
        color: 'black',
        fontFamily: 'Caladea-Bold',
        fontSize: 24,
    },
    textParentProfileSuccess: {
        color: 'white',
        fontFamily: 'Caladea-Bold',
        fontSize: 32,
        textAlign: 'center',
    },
    textForgotPassword: {
        color: 'black',
        fontFamily: 'Caladea-Bold',
        fontSize: 32,
    },
    buttonParentProfileSuccess: {
        justifyContent: 'center',
        alignItems: 'center',
        gap: 10,
        borderRadius: 30,
        backgroundColor: '#7EC845',
        width: 321,
        height: 57,
    },
    textButtonParentProfileSuccess: {
        color: 'white',
        fontFamily: 'RadioCanada',
        fontSize: 24,
    },
    buttonBackArrow: {
        width: 66,
        height: 66,
        backgroundColor: '#007EB1',
        borderRadius: 60,
        justifyContent: 'center',
        alignItems: 'center',
    },
    buttonGender: {
        width: 163,
        height: 163,
        flexShrink: 0,
        borderRadius: 90,
        justifyContent: 'center',
        alignItems: 'center',
    },
    buttonNext: {
        width: 336,
        height: 57,
        backgroundColor: '#007EB1',
        borderRadius: 30,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonDiet: {
        width: 22,
        height: 22,
        borderWidth: 2,
        borderColor: 'black',
        borderRadius: 20,
    },
    textDietName: {
        color: '#000',
        textAlign: 'left',
        fontFamily: 'RadioCanada',
        fontSize: 18,
    },
    textArticle: {
        color: '#FFF',
        fontFamily: 'RadioCanada',
        fontSize: 18,
    },
    textVideo: {
        color: '#686868',
        fontFamily: 'RadioCanada',
        fontSize: 18,
    },
    textVideoBut: {
        color: 'white',
        fontFamily: 'RadioCanada',
        fontSize: 18,
    },
    textDietName2: {
        color: '#000',
        fontFamily: 'RadioCanada',
        fontSize: 18,
    },
    textDietName1: {
        color: '#FFF',
        textAlign: 'left',
        fontFamily: 'RadioCanada',
        fontSize: 20,
        fontWeight: '600',
    },
    categoryName: {
        width: 222,
        height: 44,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 30,
        backgroundColor: '#007EB1',
    },
    naming: {
        color: '#FFF',
        textAlign: 'center',
        fontFamily: 'Caladea-Bold',
        fontSize: 24,
        marginBottom: 11,
    },
    productIngridients: {
        width: 348,
        color: '#000',
        textAlign: 'center',
        fontFamily: 'RadioCanada',
        fontSize: 20,
    },
    productIngridients1: {
        color: '#000',
        fontFamily: 'RadioCanada',
        fontSize: 20,
    },
    smallGreyText: {
        color: '#92949B',
        fontFamily: 'RadioCanada',
        fontSize: 16,
    },
    smallBlackName: {
        color: '#000',
        fontFamily: 'Caladea-Bold',
        fontSize: 20,
    },
    smallBlackText: {
        color: 'black',
        fontFamily: 'RadioCanada',
        fontSize: 16,
    },
    smallWhiteText: {
        color: 'white',
        fontFamily: 'RadioCanada',
        fontSize: 16,
    },
    bigButtonText: {
        color: '#FFF',
        textAlign: 'center',
        fontFamily: 'RadioCanada',
        fontSize: 26,
    },
    bigButtonText1: {
        color: 'black',
        textAlign: 'center',
        fontFamily: 'RadioCanada',
        fontSize: 26,
    },
    articleLikeText1: {
        color: 'black',
        fontFamily: 'RadioCanada',
        fontSize: 26,
    },
    skipText: {
        color: '#92949B',
        fontFamily: 'RadioCanada',
        fontSize: 26,
    },
    bigBlueButton: {
        width: 325,
        height: 59, // Adjust the height according to your design
        alignItems: 'center',
        justifyContent: 'center', // Center the content vertically
        borderRadius: 30,
        backgroundColor: '#007EB1',
    },
    buttonContent: {
        flex: 1,
        flexDirection: 'row',
        gap: 8,
        paddingTop: 10,
        paddingBottom: 10,
    },
    editButton: {
        width: 153,
        height: 46,
        alignItems: 'center',
        justifyContent: 'center', // Center the content vertically
        borderRadius: 30,
        backgroundColor: '#5CA6CE',
    },
    editButtonText: {
        color: '#FFF',
        textAlign: 'center',
        fontFamily: 'RadioCanada',
        fontSize: 20,
    },
    editButtonContent: {
        flex: 1,
        flexDirection: 'row',
        gap: 6,
        paddingTop: 6,
        paddingBottom: 6,
    },
    modalButton: {
        width: 141,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center', // Center the content vertically
        borderRadius: 30,
        backgroundColor: '#EA6448',
    },
    modalButtonContent: {
        flex: 1,
        flexDirection: 'row',
        gap: 6,
        paddingTop: 6,
        paddingBottom: 6,
    },
    bigAddButton: {
        width: 300,
        height: 57,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 30,
        backgroundColor: '#007EB1',
    },
    menuExampleAge: {
        width: 157,
        height: 49,
        backgroundColor: '#C4BAE6',
        borderRadius: 60,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 7,
        marginBottom: 15,
    },
    smallBlueName: {
        color: '#123955',
        fontFamily: 'Caladea-Bold',
        fontSize: 16,
    },
    smallBlueText: {
        color: '#123955',
        fontFamily: 'RadioCanada',
        fontSize: 13,
    },
    smallDescriptText: {
        color: '#000',
        fontFamily: 'RadioCanada',
        fontSize: 14,
    },
});

export default globalStyles;
