import { useNavigation } from '@react-navigation/native';
export const meals = [
    {
        id: 1,
        backgroundColor: '#FAE03C',
        imageSource: require('../assets/productImage.png'),
        title: "Breakfast",
        name: "Morning Bowl",
        width: 297,
        height: 297,
        width1: 236,
        height1: 75,
        widthImg: 219,
        heightImg: 212,
        fontSize1: 16,
        widthText: 150,
        heightText: 17,
        titleBut: "View",
        ingridients: "Organic whole grain oats (contains wheat) and organic red quinoa and organic farro (wheat) cooked in water, organic banana puree, water, organic tapioca starch, organic dried mango, organic dried pineapple, organic lemon juice concentrate, natural vanilla flavor, deoiled sunflower lecithin (for texture), iron (ferrous sulfate).",
          smallIngridients:"Oats, red quinoa & farro with tropical fruits",
          kkal:278,
          time:"10",
          ageCategory:"Crawler",
          ageMonth:"8-12",
          ageCategoryImg: require('../assets/icons/crawlerOrangeIcon.png'),
          smallProduct1: require('../assets/smallProduct1.png'),
          smallProduct2: require('../assets/smallProduct2.png'),
          smallProduct3: require('../assets/smallProduct3.png'),
          smallProduct4: require('../assets/smallProduct4.png'),
          price:"2.63",
          size:"1 bowl(128g)",
          time:"15",
    },
    {
      id: 2,
      backgroundColor: '#C6EC7A',
      imageSource: require('../assets/productImg2.png'),
      title: "Snack 1",
      name: "Strawberry Yogurt Melts",
      width: 297,
      height: 297,
      width1: 236,
      height1: 75,
      widthImg: 219,
      heightImg: 212,
      fontSize1: 16,
      widthText: 150,
      heightText: 17,
      titleBut: "View",
      ingridients: "Сultured reduced fat milk, sugar, strawberry puree, nonfat dry milk, tapioca starch, less than 1.5% of: gelatin, natural strawberry flavor, lactic acid esters of mono and diglycerides, fruit and vegetable juice colors, vitamin c (sodium ascorbate), vitamin e (alpha tocopheryl acetate), vitamin a acetate.",
      smallIngridients:"Freeze-dried yogurt snack with strawberry",
      kkal:153,
      time:"5",
      ageCategory:"Crawler",
      ageMonth:"8-12",
      ageCategoryImg: require('../assets/icons/crawlerOrangeIcon.png'),
      smallProduct1: require('../assets/smallProduct5.png'),
      smallProduct2: require('../assets/smallProduct6.png'),
      smallProduct3: require('../assets/smallProduct7.png'),
      smallProduct4: require('../assets/smallProduct8.png'),
      price:"2.63",
      size:"1 bowl(128g)",
      time:"5",
      
    },
    { id: 3,
      backgroundColor: '#C4BAE6',
      imageSource: require('../assets/productImg3.png'),
      title: "Snack 2",
      name: "Organic Lil' Crunchies",
      width: 297,
      height: 297,
      width1: 236,
      height1: 75,
      widthImg: 219,
      heightImg: 212,
      fontSize1: 16,
      widthText: 150,
      heightText: 17,
      titleBut: "View",
      ingridients: "Organic dried navy beans, organic rice flour, organic high oleic sunflower oil, organic cheddar cheese (organic cultured milk, salt, enzymes), sea salt, organic sweet whey, organic lemon juice concentrate, organic dried broccoli, organic garlic oil, organic onion oil, organic black pepper oil.",
      smallIngridients:"Crunchies with broccoli, cheddar and navy beans",
      kkal:196,
      time:"5",
      ageCategory:"Toddler",
      ageMonth:"12+",
      ageCategoryImg: require('../assets/icons/toddlerGreenIcon.png'),
      smallProduct1: require('../assets/smallProduct9.png'),
      smallProduct2: require('../assets/smallProduct10.png'),
      smallProduct3: require('../assets/smallProduct11.png'),
      smallProduct4: require('../assets/smallProduct12.png'),  
      price:"2.63",
      size:"1 bowl(128g)",
      time:"10",
    },
    {
      id: 4,
      backgroundColor: '#FFC4BC',
      imageSource: require('../assets/productImage.png'),
      title: "Lunch",
      name: "Harvest Bowl",
      width: 297,
      height: 297,
      width1: 236,
      height1: 75,
      widthImg: 219,
      heightImg: 212,
      fontSize1: 16,
      widthText: 150,
      heightText: 17,
      titleBut: "View",
      ingridients: "Organic dried navy beans, organic rice flour, organic high oleic sunflower oil, organic cheddar cheese (organic cultured milk, salt, enzymes), sea salt, organic sweet whey, organic lemon juice concentrate, organic dried broccoli, organic garlic oil, organic onion oil, organic black pepper oil.",
      smallIngridients:"Crunchies with broccoli, cheddar and navy beans",
      kkal:196,
      time:"5",
      ageCategory:"Toddler",
      ageMonth:"12+",
      ageCategoryImg: require('../assets/icons/toddlerGreenIcon.png'),
      smallProduct1: require('../assets/smallProduct9.png'),
      smallProduct2: require('../assets/smallProduct10.png'),
      smallProduct3: require('../assets/smallProduct11.png'),
      smallProduct4: require('../assets/smallProduct12.png'),
      price:"2.63",
      size:"1 bowl(128g)",
      time:"5",
    },
    
    {id: 5,
      backgroundColor: '#D5EBF4',
      imageSource: require('../assets/productImage.png'),
      title: "Snack 3",
      name: "Banana puffs",
      width: 297,
      height: 297,
      width1: 236,
      height1: 75,
      widthImg: 219,
      heightImg: 212,
      fontSize1: 16,
      widthText: 150,
      heightText: 17,
      titleBut: "View",
      ingridients: "Organic dried navy beans, organic rice flour, organic high oleic sunflower oil, organic cheddar cheese (organic cultured milk, salt, enzymes), sea salt, organic sweet whey, organic lemon juice concentrate, organic dried broccoli, organic garlic oil, organic onion oil, organic black pepper oil.",
      smallIngridients:"Crunchies with broccoli, cheddar and navy beans",
      kkal:196,
      time:"5",
      ageCategory:"Toddler",
      ageMonth:"12+",
      ageCategoryImg: require('../assets/icons/toddlerGreenIcon.png'),
      smallProduct1: require('../assets/smallProduct9.png'),
      smallProduct2: require('../assets/smallProduct10.png'),
      smallProduct3: require('../assets/smallProduct11.png'),
      smallProduct4: require('../assets/smallProduct12.png'),
      price:"2.63",
      size:"1 bowl(128g)",
      time:"6",
    },
    {id: 6,
      backgroundColor: '#FFA64F',
      imageSource: require('../assets/productImage.png'),
      title: "Dinner",
      name: "Pasta Stars",
      width: 297,
      height: 297,
      width1: 236,
      height1: 75,
      widthImg: 219,
      heightImg: 212,
      fontSize1: 16,
      widthText: 150,
      heightText: 17,
      titleBut: "View",
      ingridients: "Organic dried navy beans, organic rice flour, organic high oleic sunflower oil, organic cheddar cheese (organic cultured milk, salt, enzymes), sea salt, organic sweet whey, organic lemon juice concentrate, organic dried broccoli, organic garlic oil, organic onion oil, organic black pepper oil.",
      smallIngridients:"Crunchies with broccoli, cheddar and navy beans",
      kkal:196,
      time:"5",
      ageCategory:"Toddler",
      ageMonth:"12+",
      ageCategoryImg: require('../assets/icons/toddlerGreenIcon.png'),
      smallProduct1: require('../assets/smallProduct9.png'),
      smallProduct2: require('../assets/smallProduct10.png'),
      smallProduct3: require('../assets/smallProduct11.png'),
      smallProduct4: require('../assets/smallProduct12.png'),
      price:"2.63",
      size:"1 bowl(128g)",
      time:"10",

    },
  ];
  
  export function getMealCardsWithNavigation() {
    const navigation = useNavigation(); // Отримайте navigation
    return mealCards.map(mealCard => ({
      ...mealCard,
      onButtonPress: () => mealCard.onButtonPress(navigation), // Викликаємо onButtonPress із navigation
    }));
  }
  