import { useNavigation } from '@react-navigation/native';
export const videos = [
    {
        id: 1,
        imageSource:require('../assets/video.png'),
        title:"Carrot Cake Muffins",
        duration:"1:06 min.",
        views:"14,8k",
        ingridients: "Organic dried navy beans, organic rice flour, organic high oleic sunflower oil, organic cheddar cheese (organic cultured milk, salt, enzymes).",
        mealVideoImg:require('../assets/mealVideoImg.png'),
        youtubeId: 'Ng7k7vhHo58',
    },
    {
      id: 2,
      imageSource:require('../assets/video4.png'),
      title:"Banana Oatmeal Waffels",
      duration:"0:48 min.",
      views:"15,6k",
      ingridients: "Сultured reduced fat milk, sugar, strawberry puree, nonfat dry milk, tapioca starch, less than 1.5% of: gelatin, natural strawberry flavor, lactic acid esters of mono and diglycerides, fruit and vegetable juice colors, vitamin c (sodium ascorbate), vitamin e (alpha tocopheryl acetate), vitamin a acetate.",
      mealVideoImg:require('../assets/smallProduct5.png'),
      youtubeId:'SkGAWs-j4QQ',
    },
    { id: 3,
        imageSource:require('../assets/video5.png'),
        title:"Butternut squash mac & cheese",
        duration:"1:02 min.",
        views:"9,8k",
        ingridients: "Organic dried navy beans, organic rice flour, organic high oleic sunflower oil, organic cheddar cheese (organic cultured milk, salt, enzymes).",
        mealVideoImg:require('../assets/smallProduct1.png'),
        youtubeId:'aO48oLQn2Z4',
    },
    {
      id: 4,
      imageSource:require('../assets/video6.png'),
      title:"Carrot Cake Muffins",
      duration:"1:06 min.",
      views:"14,8k",
      ingridients: "Organic dried navy beans, organic rice flour, organic high oleic sunflower oil, organic cheddar cheese (organic cultured milk, salt, enzymes).",
      mealVideoImg:require('../assets/mealVideoImg.png'),
      youtubeId:'nnCBoKFds_0',
    },
    
    {id: 5,
        imageSource:require('../assets/video7.png'),
        title:"Butternut squash mac & cheese",
        duration:"1:06 min.",
        views:"14,8k",
        ingridients: "Organic dried navy beans, organic rice flour, organic high oleic sunflower oil, organic cheddar cheese (organic cultured milk, salt, enzymes).",
        mealVideoImg:require('../assets/mealVideoImg.png'),
        youtubeId:'Q5B5cqvwiXQ',
    },
    {id: 6,
        imageSource:require('../assets/video8.png'),
        title:"Congratulations",
        duration:"1:06 min.",
        views:"14,8k",
        ingridients: "Organic dried navy beans, organic rice flour, organic high oleic sunflower oil, organic cheddar cheese (organic cultured milk, salt, enzymes).",
        mealVideoImg:require('../assets/mealVideoImg.png'),
        youtubeId:'Yb8KqXj6tX0',
    },
  ];
  

  